import {
  LayoutDashboard,
  DoorOpen,
  Building2,
} from "lucide-react";

import {
  RentRecord,
  RentStatus,
  Unit,
  UnitStatus,
  Tenant,
  PoolCrewMember,
} from "../../../types/types";

export const NAV_ITEMS = [
  { label: "Dashboard", icon: <LayoutDashboard size={20} />, path: "/dashboard" },
  { label: "Properties", icon: <Building2 size={20} />, path: "/properties" },
  { label: "Units", icon: <DoorOpen size={20} />, path: "/units" },
];

export const MOCK_TENANTS: Tenant[] = [
  {
    id: "1",
    name: "Alex Thompson",
    unitNumber: "101",
    phone: "+91 98765 43210",
    rentAmount: 12000,
    rentStatus: RentStatus.PAID,
    noticePeriod: false,
    joiningDate: "2023-10-15",
  },
  {
    id: "2",
    name: "Sarah Jenkins",
    unitNumber: "102",
    phone: "+91 87654 32109",
    rentAmount: 11500,
    rentStatus: RentStatus.DUE,
    noticePeriod: true,
    noticeEndDate: "2024-06-30",
    joiningDate: "2023-11-20",
  },
  {
    id: "3",
    name: "Michael Chen",
    unitNumber: "204",
    phone: "+91 76543 21098",
    rentAmount: 12500,
    rentStatus: RentStatus.PAID,
    noticePeriod: false,
    joiningDate: "2024-01-10",
  },
  {
    id: "4",
    name: "Priya Sharma",
    unitNumber: "301",
    phone: "+91 65432 10987",
    rentAmount: 11000,
    rentStatus: RentStatus.OVERDUE,
    noticePeriod: false,
    joiningDate: "2023-09-05",
  },
  {
    id: "5",
    name: "David Wilson",
    unitNumber: "101",
    phone: "+91 54321 09876",
    rentAmount: 12000,
    rentStatus: RentStatus.PAID,
    noticePeriod: false,
    joiningDate: "2024-02-14",
  },
  {
    id: "6",
    name: "Emma Watson",
    unitNumber: "202",
    phone: "+91 43210 98765",
    rentAmount: 13000,
    rentStatus: RentStatus.DUE,
    noticePeriod: false,
    joiningDate: "2024-03-22",
  },
];

export const MOCK_UNITS: Unit[] = [
  {
    id: "r1",
    unitNumber: "101",
    capacity: 2,
    occupancy: 2,
    status: UnitStatus.OCCUPIED,
    floor: 1,
    type: "room",
    rent: 12000,
    deposit: 24000,
    description: "Standard double room",
    isOccupied: true,
  },
  {
    id: "r2",
    unitNumber: "102",
    capacity: 1,
    occupancy: 1,
    status: UnitStatus.NOTICE,
    floor: 1,
    type: "room",
    rent: 11500,
    deposit: 23000,
    description: "Single room with balcony",
    isOccupied: true,
  },
  {
    id: "r3",
    unitNumber: "103",
    capacity: 2,
    occupancy: 0,
    status: UnitStatus.AVAILABLE,
    floor: 1,
    type: "room",
    rent: 12000,
    deposit: 24000,
    description: "Spacious double room",
    isOccupied: false,
  },
  {
    id: "r4",
    unitNumber: "201",
    capacity: 3,
    occupancy: 1,
    status: UnitStatus.AVAILABLE,
    floor: 2,
    type: "room",
    rent: 10000,
    deposit: 20000,
    description: "Triple sharing room",
    isOccupied: false,
  },
  {
    id: "r5",
    unitNumber: "202",
    capacity: 2,
    occupancy: 2,
    status: UnitStatus.OCCUPIED,
    floor: 2,
    type: "room",
    rent: 13000,
    deposit: 26000,
    description: "Deluxe double room",
    isOccupied: true,
  },
  {
    id: "r6",
    unitNumber: "301",
    capacity: 1,
    occupancy: 1,
    status: UnitStatus.OCCUPIED,
    floor: 3,
    type: "room",
    rent: 15000,
    deposit: 30000,
    description: "Penthouse room",
    isOccupied: true,
  },
];

export const MOCK_RENTS: RentRecord[] = [
  {
    id: "rt1",
    tenantName: "Alex Thompson",
    tenantId: "1",
    unitNumber: "101",
    month: "May 2024",
    amount: 12000,
    dueDate: "2024-05-05",
    status: RentStatus.PAID,
  },
  {
    id: "rt2",
    tenantName: "Sarah Jenkins",
    tenantId: "2",
    unitNumber: "102",
    month: "May 2024",
    amount: 11500,
    dueDate: "2024-05-05",
    status: RentStatus.DUE,
  },
  {
    id: "rt3",
    tenantName: "Michael Chen",
    tenantId: "3",
    unitNumber: "204",
    month: "May 2024",
    amount: 12500,
    dueDate: "2024-05-05",
    status: RentStatus.PAID,
  },
  {
    id: "rt4",
    tenantName: "Priya Sharma",
    tenantId: "4",
    unitNumber: "301",
    month: "May 2024",
    amount: 11000,
    dueDate: "2024-05-05",
    status: RentStatus.OVERDUE,
  },
];


export const STAT_COLORS = {
  TOTAL: "text-blue-500 bg-blue-100 dark:bg-blue-900/20",
  ONBOARD: "text-indigo-500 bg-indigo-100 dark:bg-indigo-900/20",
  AVAILABLE: "text-emerald-500 bg-emerald-100 dark:bg-emerald-900/20",
  ALERTS: "text-red-500 bg-red-100 dark:bg-red-900/20",
  ASSIGNED: "text-blue-500 bg-blue-100 dark:bg-blue-900/20",
  PENDING: "text-amber-600 bg-amber-100 dark:bg-amber-900/20", 
  COMPLETED: "text-slate-600 bg-slate-100 dark:bg-slate-800",
} as const;


export const MOCK_CREW: PoolCrewMember[] = [
  {
    id: "1",
    firstName: "Rajveer",
    lastName: "Singh",
    rank: "3rd Officer",
    code: "CRW-32",
    status: "ONBOARD",
    vessel: "Black Pearl",
    nationality: null,
    joinDate: "16 Jun 2026",
    contractType: "3rd Officer · 6 mo",
    shoreOn: "03 Jun 2026",
    shipOn: "05 Jun 2026"
  },
  {
    id: "2",
    firstName: "Raman",
    lastName: "Yadav",
    rank: "Chief Officer",
    code: "CRW-001",
    status: "ONBOARD",
    vessel: "Black Pearl",
    nationality: "Indian",
    joinDate: "01 May 2026",
    contractType: "Chief Officer · 4 mo",
    shoreOn: "20 Apr 2026",
    shipOn: "25 Apr 2026"
  },
  {
    id: "3",
    firstName: "Utkarsh",
    lastName: "Jha",
    rank: "Chief Officer",
    code: "CREW-001",
    status: "ASSIGNED",
    vessel: "Black Pearl",
    nationality: "Indian",
    joinDate: "10 Jul 2026",
    contractType: "Chief Officer · 4 mo",
    shoreOn: "01 Jul 2026",
    shipOn: "05 Jul 2026"
  },
];